/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IDModel (
  iD: Option[String],
  name: Option[String],
  parentID: Option[String],
  hasShelfLife: Option[String],
  isByProduct: Option[String],
  recipieName: Option[String],
  shelfLife: Option[String],
  displayIndex: Option[String],
  iconName: Option[String],
  notes: Option[String],
  uOM: Option[String],
  isExcludedFromOpt: Option[String],
  isPlannedAfterOpt: Option[String]
) extends ApiModel


