/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class MasterConfigModel (
  productCode: Option[Double],
  description: Option[String],
  supplier: Option[String],
  stockingPointID: Option[Double],
  needsLooseBOM: Option[Double],
  live: Option[Double],
  unitID: Option[String],
  siteID: Option[String],
  lane: Option[String],
  constraint: Option[String],
  laneGroup: Option[String],
  laneLeg: Option[String],
  destinationStockingPoint: Option[String],
  inOut: Option[String],
  truckIdentity: Option[String],
  leadTime: Option[String]
) extends ApiModel


