/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class RoutingConfiguratorViewModel (
  edgeThickness: Option[Double],
  fontName: Option[String],
  fontSize: Option[Double],
  gridHeight: Option[Double],
  gridPointDistance: Option[Double],
  gridWidth: Option[Double],
  iD: Option[Double],
  isCompactMode: Option[String],
  isGridVisible: Option[String],
  offsetX: Option[Double],
  offsetY: Option[Double],
  operationInHeight: Option[Double],
  operationInputOutoutWidth: Option[Double],
  operationOffsetX: Option[Double],
  operationOffsetY: Option[Double],
  operationWidth: Option[Double],
  padding: Option[Double],
  pISPHeight: Option[Double],
  pISPWidth: Option[Double],
  routingStepDistance: Option[Double],
  routingStepMinimumHeight: Option[Double],
  routingStepMinimumWidth: Option[Double],
  user: Option[String],
  userOperationInputOutputHeight: Option[Double]
) extends ApiModel


