/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class StockingPointModel (
  iD: Option[String],
  name: Option[String],
  displayIndex: Option[String],
  iconName: Option[String],
  currencyID: Option[String],
  isPlannedInfinite: Option[String],
  groupName: Option[String],
  gISCountryCode: Option[String],
  gISCity: Option[String],
  gISPostalCode: Option[String],
  start: Option[String],
  end: Option[String],
  notes: Option[String]
) extends ApiModel


