/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class TransportCapacitiesModel (
  hasSecondaryCapacity: Option[String],
  lotSize: Option[Double],
  start: Option[Double],
  timeUnit: Option[String],
  unitID: Option[String],
  maxCapacity: Option[Double],
  minCapacity: Option[Double],
  secondaryLotSize: Option[Double],
  secondaryMaxCapacity: Option[Double],
  secondaryMinCapacity: Option[Double],
  secondaryUOM: Option[Double]
) extends ApiModel


