/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Units (
  iD: Option[String],
  parentUnitID: Option[String],
  displayIndex: Option[String],
  name: Option[String],
  quantityToProcess: Option[String],
  iconName: Option[String],
  capacityType: Option[String],
  currencyID: Option[String],
  startDate: Option[String],
  endDate: Option[String],
  isPlannedInfinite: Option[String],
  unitofMeasureName: Option[String],
  groupName: Option[String],
  minQuantity: Option[String],
  lotSize: Option[String],
  gISCountryCode: Option[String],
  gISCity: Option[String],
  gISPostalCode: Option[String],
  hasMaximumQuantity: Option[String],
  hasCapacitySmoothing: Option[String],
  hasCapacitySmoothingLength: Option[String],
  capacitySmoothinPercentageDelta: Option[String],
  isOverlapCapacitySmoothing: Option[String],
  isSmoothCapacityOverAllPeriods: Option[String],
  notes: Option[String],
  campaignTypeDuration: Option[String],
  isIncludedInSupplySpecification: Option[String],
  userFrozenFutureDuration: Option[String],
  hasUserFrozenFutureDuration: Option[String]
) extends ApiModel


