/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class UnitAvalibilitiesModel (
  allocation: Option[Double],
  efficency: Option[Double],
  maintenance: Option[Double],
  maxLoadPercentage: Option[Double],
  minLoadThreshold: Option[Double],
  nrOfUnitsOpen: Option[Double],
  shiftPatternName: Option[String],
  start: Option[Double],
  timeUnit: Option[String],
  unitId: Option[String]
) extends ApiModel


